version: '3.8'
services:
  terraform:
    build:
      dockerfile: terraform.dockerfile
      context: .
    volumes:
      - $PWD:/app
    working_dir: /app
  website:
    build:
      context: .
    ports:
      - 80:80
  unit-tests:
    volumes:
      - $PWD:/app
    build:
      context: .
      dockerfile: /app/rspec.dockerfile
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
